# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a57c68d71e2bd25ce0c83e407c9bfde7e07a36df650d3f9c05544feeae187dd466701ca53bb5e5d9ae739707b3e13e159e6608fee8337fe3db3e14e156b54e40

test:
  secret_key_base: ac3a6bdb8eaf14ac4062cabacd6829fd795ccd49a98ac304df47a766f4fa5601d8fceccca6fe26045e1ebf969171dda4394e92f515e6d20ccc8390652fb49395

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
